export const authenticate = async (req, res) => {
   try {
   } catch (error) {
      res.status(500).json({ success: false, message: "server error" });
   }
};
